// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordBattle.Infrastructure.Persistence;

#nullable disable

namespace WordBattle.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260802133046_AddMatchDeadlineAndCompletionReason")]
    partial class AddMatchDeadlineAndCompletionReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WordBattle.Domain.Entities.GameMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletionReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetWord")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("WinnerPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("WinnerPlayerId");

                    b.ToTable("GameMatches", (string)null);
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.GameWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanBeTarget")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("GameWords", null, t =>
                        {
                            t.HasCheckConstraint("CK_GameWords_Length_Positive", "\"Length\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "AKŞAM"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "ARMUT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "BAHAR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "BALIK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "BAVUL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "BEBEK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "BİBER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "BİLEK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "BULUT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "CEVİZ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "ÇİÇEK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "ÇORAP"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "DAMAR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "DEMİR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "DENİZ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "DÜĞÜN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "EKMEK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "ELMAS"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "FIRIN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "GÖLET"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "GÜNEŞ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "HAMUR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "HAVUÇ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "İNCİR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KALEM"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KANAT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KAPAK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KAVUN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KEMER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KİRAZ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KİTAP"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KÖPRÜ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KUMRU"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KUTUP"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "KUYRU"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "MASAL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "MEYVE"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "ORMAN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "OYNAK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "PAZAR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "SABAH"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "SAHİL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "SEPET"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "ŞEHİR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "TABAK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "TAVUK"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "TOPUZ"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "YAPIT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "YILAN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            CanBeTarget = true,
                            CreatedAt = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Length = 5,
                            Text = "YOLCU"
                        });
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.Guess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Guesses", (string)null);
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RematchRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RematchRequestedByPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.RoomPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PlayerToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerToken");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomPlayers", (string)null);
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.GameMatch", b =>
                {
                    b.HasOne("WordBattle.Domain.Entities.Room", "Room")
                        .WithMany("Matches")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordBattle.Domain.Entities.RoomPlayer", null)
                        .WithMany()
                        .HasForeignKey("WinnerPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.Guess", b =>
                {
                    b.HasOne("WordBattle.Domain.Entities.GameMatch", "Match")
                        .WithMany("Guesses")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordBattle.Domain.Entities.RoomPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.RoomPlayer", b =>
                {
                    b.HasOne("WordBattle.Domain.Entities.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.GameMatch", b =>
                {
                    b.Navigation("Guesses");
                });

            modelBuilder.Entity("WordBattle.Domain.Entities.Room", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
